### ISSUE TITLE
[Feature] make dynamic routes from config

### ISSUE THREAD

**Issue by jwiegant** [tomatophp/filament-developer-gate#1]
We would like to be able to set the route to a different one. Now it's fixed to /admin.

**Comment by fadymondy** [comment]
hi @jwiegant thanks for your report i will check if the problem exists and I will fix it ASAP

**Comment by fadymondy** [comment]
after v1.0.4

now you can change the route prefix from the config

```bash
php artisan vendor:publish --tag="filament-developer-gate-config"
```

than 

```php
<?php

return [
    "route_prefix" => "admin"
];

```

change admin to any name you want then

```bash
php artisan config:cache
```
